#!/sbin/busybox sh

export BOOTREC_CACHE_NODE="/dev/block/mtdblock2 b 31 2"
export BOOTREC_CACHE="/dev/block/mtdblock2"
export BOOTREC_EVENT_NODE="/dev/input/event2 c 13 66"
export BOOTREC_EVENT="/dev/input/event2"
export BOOTREC_LED_RED="/sys/class/leds/red"
export BOOTREC_LED_GREEN="/sys/class/leds/green"
export BOOTREC_LED_BLUE="/sys/class/leds/blue"
export BOOTREC_LED_BUTTONS="/sys/class/leds/button-backlight"
export BOOTREC_LED_LCD="/sys/class/leds/lcd-backlight"

export BOOTREC_LED_RED_CURRENT="5000"
export BOOTREC_LED_GREEN_CURRENT="5000"
export BOOTREC_LED_BLUE_CURRENT="5000"
export BOOTREC_LED_BUTTONS_CURRENT="500"
export BOOTREC_LED_LCD_CURRENT="21000"
